algoritmo "escolhatimes"
// Função :
// Autor :
// Data : 16/08/2022
// Seção de Declarações 
var
times:caracter
inicio
escreval("digite o nome do seu time")
leia(times)
escolha times
caso "curintia","palmeiras","santos","sao paulo"
     escreval("seu time é do eixo paulista")
caso "vascao","botafogo","mengo","flu"
     escreval("seu time é do eixo carioca")
outrocaso
         escreval("inválido")
fimescolha
fimalgoritmo
