algoritmo "Exemplo_01"
// Função : Exemplo de condicional simples
// Autor : Giovanni Caramello Grego
// Data : 26/07/2022
// Seção de Declarações 
var
idade:inteiro
inicio
escreval("Informe sua idade: ")
leia (idade)
se idade>=18 entao
   escreval("Pode Passar")
   escreval("VERDADEIRO")
senao
   escreval("Não Pode Passar")
   escreval("FALSO")
FimSe
escreval("ACABOU . . . .")
fimalgoritmo
