Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/11/2022
Var
i,n,soma:inteiro
numeros: vetor[1..10] de inteiro
Inicio
para i de 1 ate 10 faca
 escreval("informe o valor ",i)
      leia(n)
      soma<-soma+n
   fimpara
   escreval("a soma é: ",soma)


Fimalgoritmo