algoritmo "semnome"
// Função :
var
ronaldofenomeno,ronaldinhobruxo,zico,robertocarlos: inteiro
cafu:real
inicio
para ronaldofenomeno de 1 ate 5 faca
 escreval("digite um numero: ")
 leia(ronaldinhobruxo)
se (ronaldinhobruxo mod 2 = 0) entao
    zico <- zico + ronaldinhobruxo
    robertocarlos <- robertocarlos + 1
fimse
fimpara
escreval("a soma é: ",zico)
escreval("achei ",robertocarlos," de pares")
cafu <- (zico / robertocarlos)
escreval(" a média é:  ",cafu)
fimalgoritmo
