algoritmo "semnome"
// Função : laço de repetição
var
contador:inteiro
inicio
//contador <- 10
//repita
//      escreval(contador)
//      contador <- contador - 1
//ate (contador<1)







//contador <- 10
//enquanto (contador>0) faca
//        escreval(contador)
//        contador <- contador - 1
//fimenquanto






//para contador de 10 ate 1 passo -1 faca
 //    escreval(contador)
//fimpara

fimalgoritmo
