algoritmo "Fibonacci"
// Função : fibonacci
// Autor :
// Data : 06/09/2022
// Seção de Declarações 
var
val,val2,val3,limit,conta:inteiro
inicio
escreva("informe o limite:  ")
leia(limit)
val<-1
val2<-0
conta<-0
enquanto (conta<limit) faca
         val3<-val+val2
         val<-val2
         val2<-val3
         escreva(val3)
         conta<-conta+1


fimenquanto

fimalgoritmo
